### ISSUE TITLE
Custom Timers and Yield/Resume?

### ISSUE THREAD

**Issue by Mike-EEE** [nblumhardt/serilog-timings#1]
First off... what an incredible design and approach around this topic.  This has HOUNDED me for many many years and all of my solutions around it have been terrible! LOL.  It's so great to see this topic/concern tackled in a Serilog/Seq/Blumhardt way and to get some great clarity/perspective guidance around this.

With that said, I mentioned this in [your incredible blog post](http://nblumhardt.com/2016/04/serilog-timings/), but I have spent the past two weeks or so trying to nail down a good solution (which I clearly am not happy with anymore now that this project exists!) around this.  I based it from [PostSharp's Profiler aspect](http://samples.postsharp.net/#PostSharp.Samples.Profiling/ProfileAttribute.cs).  One thing you'll notice is that it makes use of both `Stopwatch` and `GetThreadTimes` timers.

So, since you have a lot more context around this than I do, I am curious on what the benefit is for using the `GetThreadTimes` (or "CPU time" as it is emitted).  And, if this is valuable, is this something that can be added as a feature to Serilog Timings?  Obviously, since this is a native Windows feature, it should be something that is created as such (basically what I spent so much time with in my implementation).

Also, I am curious about method pausing/resuming as the aspect accounts for... is this something that Serilog Timings accounts for, and if not... something perhaps that can be added?

Thanks again for making this great project!

**Comment by nblumhardt** [comment]
Thanks for the note, Mike! I don't think the design of this API is within the kinds of tolerances required for code-level profiling, which I think the `GetThreadTimes()` function is covering.

In the monitoring scenarios I'm most interested in myself, it's generally desirable to include time spent awaiting asynchronous operations - which include most DB and network calls in modern .NET apps.

I think tools to deal with code-level profiling and wait-exclusive time are an interesting area, but I don't think the scope of this library should expand that far (aiming for small-and-sharp at this stage).

Thanks again for the feedback though, and let me know if I misunderstood!

Cheers,
Nick

**Comment by Mike-EEE** [comment]
OK... I'm with you.  So basically I could continue to use my `ProfileAttribute` for local code profiling scenarios, and then a (theoretical) `OperationAttribute` for external/integration scenarios.  I will adjust accordingly. :)  Thanks for the feedback/direction!
