### ISSUE TITLE
Send Serilog ILogger to Begin and Time methods

### ISSUE THREAD

**Issue by stanisls** [nblumhardt/serilog-timings#28]
I just started using Serilog Tmings for exacly the reasons you outlined in your 2016 blog.
However, there is one construct that I am missing.

Each class has a 

`private readonly ILogger _logger;`

which is enriched with the SourceContext like this:

`_logger = Log.Logger.ForContext<MyClass>();`

Serilog.Timings expects enrichments from the LogContext, which means that every place I intend to use it, I have to resort to a verbose pattern.
I have a library of enricher extension methods, which add application-specific properties to the ILogger, like

`_logger.With(location).Information("It was here");`

I could, theoretically, push a number of properties on the LogContext, but that would just bloat the number of usings, which do not add to the code fuctionality or readability.

```
_logger.With(location).Information("It was here");
using (LogContext.PushProperty("SourceContext", GetType().FullName))
using (var opTime = Operation.Begin("Do something"))
{
 _logger.Warning("Some warning");
 opTime.Complete();
}
```

or

```
using (LogContext.PushProperty("Location", LoggerExtensions.ProcessLocationPropertyForLog(location)));
using (LogContext.PushProperty("SourceContext", GetType().FullName))
using (var opTime = Operation.Begin("Do something"))
{
 _logger.Warning("Some warning");
 opTime.Complete();
}
```

What I'd love to see is a way of passing ILogger to Begin or Time, so that I'd be able to just write:

```
using (var opTime = Operation.Begin(_logger.With(location), "Do something"))
{
 _logger.Warning("Some warning");
 opTime.Complete();
}
```

or even better:

```
using (var opTime = _logger.With(location).BeginOperation("Do something"))
{
 _logger.Warning("Some warning");
 opTime.Complete();
}
```

**Comment by nblumhardt** [comment]
Thanks for the note!

The extension methods `TimeOperation()` and `BeginOperation()` are already available on `ILogger`: https://github.com/nblumhardt/serilog-timings#use-with-ilogger

Your final code sample should be able to be written as:

```csharp
using (var opTime = _logger
    .ForContext("Location", LoggerExtensions.ProcessLocationPropertyForLog(location))
    .BeginOperation("Do something"))
{
 _logger.Warning("Some warning");
 opTime.Complete();
}
```

Does this cover it? Thanks!

**Comment by stanisls** [comment]
Thank you, it definitely does.
I should have read the documentation here, instead of solely going by the blog post usage examples.
