### ISSUE TITLE
PCL Support?

### ISSUE THREAD

**Issue by Mike-EEE** [nblumhardt/serilog-timings#3]
Here we go again. :)

Looks like there is .NET Core support, and .NET 4.5.1 support, but not PCL?  Are there plans on making this a PCL-based library?

**Comment by nblumhardt** [comment]
Hi Mike - which PCL profile are you targeting? Open to trying to support any that don't require shims/#ifdefs :-)

**Comment by Mike-EEE** [comment]
Yes #ifdef's are the devil. :stuck_out_tongue: 

I am using Profile7, which basically accounts for the Big 3: iOS/Droid/Windows :)

**Comment by bbrandt** [comment]
Should this be renamed.NET Platform Standard Support at this point?

I think netstandard1.2 is a good place to start if it has all the needed library features.  Moving up to netstandard1.3 looks to drop support for full framework 4.5.2, so may exclude too many people.

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms

**Comment by nblumhardt** [comment]
Version 2.0 now on NuGet supports netstandard1.0+ so should have just about every modern option covered. How does this go for you @Mike-EEE?

Cheers!

**Comment by Mike-EEE** [comment]
Hey @nblumhardt sorry for the reply here.  I have been meaning to try this out but have been once again bamboozled by my current project.  I am apt to say that this does indeed look good.  I will definitely try this and let you know when I can. It's on my list. :)  If someone else wants to verify then all the better.  I don't want to hold up this issue so I am cool with closing it and then reopening if there is a problem.  Just checking in here to let you know.  Definitely appreciate the work done towards this! :+1:

**Comment by Mike-EEE** [comment]
HOLY COW I am just now getting back around to this.  I was able to upgrade my PCL to the new .NET standard and was able to import Serilog and all of the new incredibly modular packages, resulting in ZERO problems and all tests remaining in tact as passing!  Great work, team!

So yes, I do believe this issue is resoundingly resolved in my world.  We can mark it as closed as far as I am concerned. :star:
