### ISSUE TITLE
Is project death?

### ISSUE THREAD

**Issue by esavini** [nblumhardt/serilog-timings#39]
Hello, as I can see, this project has not received updates in the last three years. Is currently maintained?

Thank you in advance.

**Comment by nblumhardt** [comment]
I'm still using it! There isn't a lot to do (though I am overdue to loop back around and check out that PR 😁).

**Comment by EamonHetherton** [comment]
still using it here too...
@nblumhardt is pretty good at getting important fixes into the codebase and the build pipeline builds a pre-release package for you from any pull request that you can use straight away too. (I wish more projects were this contributor friendly) 

Not updated often?  that just means it's stable AF 😁
