### ISSUE TITLE
SerilogTimings not working when using NEST  and ElasticSearch.Net

### ISSUE THREAD

**Issue by dkezri** [nblumhardt/serilog-timings#40]
Hi

We have a a couple of microservices which they log to Elasticsearch. The "SerilogTimings"  works fine in all of them except the one using "ElasticSearch.net" and "Nest" nuget  packages.

--- application details:
Web api  (.Net version 5.0)
"Serilog.Enrichers.Environment" Version="2.2.0"
"Serilog.Sinks.Elasticsearch" Version="8.4.1" 
"SerilogTimings" Version="2.3.0"
"Elasticsearch.Net" Version="7.13.2"
"NEST" Version="7.13.2"

thanks for any help.

**Comment by nblumhardt** [comment]
Hi! Sounds like something specific to Elastic, this library is very simple and based only on core Serilog APIs. May be best to raise a ticket with them. HTH!
