### ISSUE TITLE
[Readme] Levelling a contextual ILogger?

### ISSUE THREAD

**Issue by melmullen** [nblumhardt/serilog-timings#45]
First, thanks to all contributors for a really useful library.

Is it possible to level a contextual logger? If it is, can we have an example please? If it is not, can you please call that out?

**Comment by nblumhardt** [comment]
Hi! You need `using SerilogTimings.Extensions`, this will light up `logger.OperationAt(...)`.

HTH,
Nick

**Comment by melmullen** [comment]
When I talk about a contextual logger I mean ILogger<MyType> which is in the Microsoft namespace. It doesn't appear that I can specify a logging level when using one of these.

**Comment by nblumhardt** [comment]
This repo is for extending Serilog/Serilog's `ILogger`. The Microsoft `ILogger` is a different thing, but you might find a "timings" library out there for it (or be able to fork/adapt this one).

**Comment by melmullen** [comment]
Sorry, GitHub ate my angle brackets (corrected now). I'm talking about the Microsoft typed Logger interface when configured to use the Serilog implementation. It appears that I can't use the typed interface if I want to use this library. I haven't used Serilog before so maybe people generally don't use it this way?

**Comment by nblumhardt** [comment]
Thanks for the reply! I understood what you meant by `ILogger` :+1:

This project is for people who are using Serilog directly, and it extends Serilog's API.

You can also choose to use MEL, and route messages from its `ILogger<T>` through Serilog, but then you're not using Serilog's API at all, and this library doesn't target that scenario.

A "MEL Timings" that shipped extension methods for MEL's `ILogger<T>` would be cool to see - it'd be a separate project, though.

Hope this helps!

**Comment by natehaby** [comment]
I've been using it with ILogger for about 2+ years. It works well. It takes about an hour to rip out the Serilog specific stuff.  I have not included a link on here only because it was quick and dirty, no tests, etc. I do not use it in anything mission critical at this time.  Doing a proper fork has been on my list, I just haven't gotten around to it.
