### ISSUE TITLE
Nested Timings

### ISSUE THREAD

**Issue by stephenpatten** [nblumhardt/serilog-timings#5]
Nested timings don't seem to pick up the parent OperationId when using Enrich.FromLogContext(), any ideas

**Comment by bbrandt** [comment]
The idea I was thinking of implementing a pull request for this was to copy the current OperationId into a ParentOperationId when a nested operation occurs.  Have yet to check if this is possible in the code.

**Comment by nblumhardt** [comment]
Closing as it's been around for a while now, still open to giving this one a shot if anyone decides to pick it up :-) Cheers!

**Comment by maleczki** [comment]
Hi Nicholas, finally, what do you recommend for timing nested operations?

**Comment by nblumhardt** [comment]
@mma42300 Hi! No current solution/opinions - using a hierarchical identifier for operation ids might be worth investigating 🤔

**Comment by mma42300** [comment]
@nblumhardt OK, thanks!
