### ISSUE TITLE
Feature: Checkpoints and ExceedanceReports

### ISSUE THREAD

**Issue by sandreas** [nblumhardt/serilog-timings#52]
What do you think about adding

- Checkpoints
- ExceedanceReports

Explanation (in Code):

```C#
var exceedTime = TimeSpan.FromSeconds(5)
using (var op = Operation.ExceedanceReport(LogEventLevel.Warn, exceedTime).Time("Creating zip archive")) {
    CopyFilesToTemp();
    op.CheckPoint("files copied to temp");
    CleanUpUnwantedFiles();
    op.CheckPoint("unwanted files deleted");
    ZipFiles();
    op.Complete("zip archive created");
}
```

Now, if the operation takes less than 5 seconds, NOTHING is logged, because of the second parameter in `Operation.ExceedanceReport`. This config produces a `Warning`, ONLY if the whole process takes more than 5 seconds.

The checkpoints result in log entries similar to the existing ones via `using ...`, but make out a *series* of timed events:

```
[WRN] files copied to temp completed in 3200 ms
[WRN] unwanted files deleted in 121 ms (3321 ms)
[WRN] zip archive created in 8433 ms (11.754 ms)
[WRN] Creating zip archive exceeded its time limit with 11.754 ms
```

Advantages:
- Checkpoints: Sometimes you want to have a detailed analysis of a process taking some steps. With the current approach, there would be many `using` statements to accomplish that 
- ExceedanceReport: In production, usually, you would like to keep your logfiles small but still want to know about performance issues (especially if its not your application, but an API or DBMS). With `ExceedanceReport` you could accomplish that easily by adding a warning to your logs, if a database query takes an ususual time or an API does not respond in a specific timespan

What do you think?

**Comment by nblumhardt** [comment]
Hi @sandreas! I think this would be really cool; I'm not really intending to expand this library though - the goal currently is to keep it ultra-simple.

I'd be really happy to see a new library (built out of a fork of this one, if you would like to), that reimagined timings for Serilog as a more sophisticated system for these kinds of operations.

If you're keen to give it a go, I'd also be happy to link it from here. Let me know if so :-)

**Comment by sandreas** [comment]
Thank you for the quick feedback.

> I'm not really intending to expand this library though - the goal currently is to keep it ultra-simple.

Perfectly fine.

> I'd be really happy to see a new library (built out of a fork of this one, if you would like to), that reimagined timings for Serilog as a more sophisticated system for these kinds of operations.

Me, too.

> If you're keen to give it a go, I'd also be happy to link it from here. Let me know if so :-)

I would love to, but unfortunately there is no time left :-) I thought that these two extensions would be low hangng fruits, since they would only be a little addition to `op.Complete`, but if this is not the case, I'll accept that.

Since this will not be implemented, should I close this issue?

**Comment by nblumhardt** [comment]
Thanks @sandreas 👍
