### ISSUE TITLE
Does not honour Logger context

### ISSUE THREAD

**Issue by ben-foster-cko** [nblumhardt/serilog-timings#7]
When using an existing logger instance, the `SourceContext` is always set to `SerilogTimings.Operation`.

Example:

```
            using (var operation = _logger.ForContext<SerilogPerfTracker>().ForContext(propertyBag)
                .OperationAt(LogEventLevel.Debug)
                .Begin("Operation {Type}.{Method}", operationClass, operationMethod))
            {
                action.Invoke();
                operation.Complete();
            }
```

**Comment by nblumhardt** [comment]
Interesting - thanks Ben. This package probably shouldn't set `SourceContext` at all. We should be able to just [remove this line](https://github.com/nblumhardt/serilog-timings/blob/dev/src/SerilogTimings/Operation.cs#L200).

**Comment by benfoster** [comment]
I'll send a PR for this.
