### ISSUE TITLE
Support passing multiple enrichers to Operation.Complete

### ISSUE THREAD

**Issue by ben-foster-cko** [nblumhardt/serilog-timings#8]
Currently, we can only pass one event log property to `Operation.Complete`. We have the need to pass multiple properties - we don't want to destructure our result object.

Could we instead pass an array of enrichers to `Operation.Complete` to "enrich" the operation result?

**Comment by benfoster** [comment]
Happy to send a PR if you're happy for me to add the following overload:

```
Complete(IEnumerable<ILogEventEnricher> resultEnrichers)
```

**Comment by nblumhardt** [comment]
Completed in #30
